---
# tasks file for npm
- name: install npm on centos 6
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: install npm on centos 7
  package:
    name: nodejs
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: install npm on fedora
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "Fedora"


- name: install npm on Alpine 3.4 and 3.5
  package:
    name: nodejs
    state: present
  when:
    - ansible_distribution == "Alpine"
    - ansible_distribution_version >= "3.4"
    - ansible_distribution_version <= "3.6"

- name: install npm on Alpine 3.6
  package:
    name: nodejs-npm
    state: present
  when:
    - ansible_distribution == "Alpine"
    - ansible_distribution_version >= "3.6"

- name: install npm requirements on Debian or Ubuntu
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg2
  when:
    - ( ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )

- name: get nodejs setup
  get_url:
    url: https://deb.nodesource.com/setup_8.x
    dest: /tmp/setup_8.x
  register: geturl
  when:
    - ( ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )

- name: run nodejs setup
  command: bash /tmp/setup_8.x
  when:
    - ( ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )

- name: install nodejs on Debian or Ubuntu
  package:
    name: nodejs
    state: present
  when:
    - ( ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )
