---
# tasks file for npm
- name: install npm on centos 6
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: install npm on centos 7
  package:
    name: nodejs
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: install npm on fedora
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "Fedora"

- name: install npm on Alpine
  package:
    name: nodejs-npm
    state: present
  when:
    - ansible_distribution == "Alpine"
    
- name: install npm on Debian or Ubuntu
  package:
    name: nodejs
    state: present
  when:
    - ( ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )
