---
# tasks file for npm
- name: install npm on centos 6
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: install npm on centos 7
  package:
    name: nodejs
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: install npm on fedora
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "Fedora"


- name: install npm on Alpine 3.4 and 3.5
  package:
    name: nodejs
    state: present
  when:
    - ansible_distribution == "Alpine"
    - ansible_distribution_version >= "3.4"
    - ansible_distribution_version <= "3.6"

- name: install npm on Alpine 3.6
  package:
    name: nodejs-npm
    state: present
  when:
    - ansible_distribution == "Alpine"
    - ansible_distribution_version >= "3.6"

- name: install npm on Ubuntu
  package:
    name: npm
    state: present
  when:
    - ansible_distribution == "Ubuntu"

- name: install npm requirements on Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg2
  when:
    - ansible_distribution == "Debian"

- name: Download nodejs setup on Debian
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /tmp/setup_6.x
  when:
    - ansible_distribution == "Debian"

- name: Run nodejs setup on Debian
  command: bash /tmp/setup_6.x && touch /tmp/setup_6.x.done
  args:
    creates: /tmp/setup_6.x.done
  when:
    - ansible_distribution == "Debian"

- name: Install nodejs on Debian
  package:
    name: nodejs
    state: present
  when:
    - ansible_distribution == "Debian"
