---
# tasks file for npm
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install nodejs key
  apt_key:
    url: "{{ npm_apt_key }}"
  when:
    - ansible_distribution == "Debian"

- name: install nodejs deb repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ npm_apt_repositories }}"
  when:
    - ansible_distribution == "Debian"

- name: install nodejs rpm repository
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ npm_gpg_key }}"
  with_items:
    - "{{ npm_yum_repositories }}"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: install npm
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ npm_packages }}"
