---
# tasks file for npm
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install nodejs key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  when:
    - ansible_distribution == "Debian"

- name: install nodejs deb repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
  when:
    - ansible_distribution == "Debian"

- name: install nodejs rpm repository
  yum_repository:
    name: nodejs
    description: NodeJS YUM repo
    baseurl: https://rpm.nodesource.com/pub_10.x/el/$releasever/$basearch/
  when:
   - ansible_distribution == "CentOS"
   - ansible_distribution_major_release == 6

- name: install npm
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ npm_packages }}"
