---
# tasks file for npm
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install nodejs repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
  when:
    - ansible_distribution == "Debian"
  notify:
    - install nodejs key

- name: flush handlers
  meta: flush_handlers

- name: install npm
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ npm_packages }}"
