---
# tasks file for npm
- name: install nodejs key
  apt_key:
    url: "{{ npm_apt_key }}"
    state: present
    validate_certs: "{{ npm_validate_certs }}"
  when:
    - ansible_distribution == "Debian"
  register: npm_install_nodejs_key
  until: npm_install_nodejs_key is succeeded
  retries: 3

- name: install nodejs deb repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ npm_apt_repositories }}"
  when:
    - ansible_distribution == "Debian"

- name: install nodejs rpm repository
  yum_repository:
    name: "{{ item.name }}"
    state: present
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ npm_gpg_key }}"
  with_items:
    - "{{ npm_yum_repositories }}"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
  loop_control:
    label: "{{ item.name }}"

- name: install npm
  package:
    name: "{{ npm_packages }}"
    state: present
  register: npm_install_npm
  until: npm_install_npm is succeeded
  retries: 3

- name: set the registry
  lineinfile:
    path: /usr/etc/npmrc
    regexp: "^registry="
    line: "registry={{ npm_registry }}"
    create: yes
