---
# tasks file for npm
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install npm
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ npm_packages }}"
