---
- name: Prepare
  hosts: all
  gather_facts: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel

  tasks:
    - name: install package with npm
      npm:
        name: debug
        global: yes
