---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.npm

  tasks:
    - name: install package with npm
      npm:
        name: debug
        global: yes
