---
- name: Converge
  hosts: all
  gather_facts: no
  strategy: free

  roles:
    - role: ansible-role-npm

  tasks:
    - name: install package with npm
      npm:
        name: debug
        global: yes
