---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: install package with npm
      npm:
        name: debug
        global: yes
      register: npm_install_package_with_npm
      until: npm_install_package_with_npm is succeeded
      retries: 3
