---
- name: Converge
  hosts: all
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: ansible-role-npm

  tasks:
    - name: install package with npm
      npm:
        name: debug
        global: yes
