---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: npm-centos-6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos-6
